### ISSUE TITLE
Blender generic FaceCap Custom Avatar Exporter

### ISSUE THREAD

**Issue by enzyme69** [hizzlehoff/FaceCapCustomAvatarExporter#1]
Hello Niels, is it possible to have Blender version of Avatar Exporter? I am reading the Maya code now and hoping that maybe we can just use it for Blender, what's the actual specifications for .FCA?

Also, with your other app "Face Scan - Blendshapes" would it also be useful to be able to export .FCA from there?

Thanks!

**Comment by hizzlehoff** [comment]
A blender exporter is now available, give it a try.
